name: Daily Hilay Script

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Allow pushing changes to the repo

jobs:
  run-hilay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hilay.py
        run: python hilay.py

      - name: Commit and push RSlintv.m3u
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add RSlink tv.m3u
          git commit -m "Auto-update M3U playlist" || echo "No changes to commit"
          git push
